# Generated by Django 3.2.4 on 2021-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoriteslist',
            name='favorites_products',
        ),
        migrations.AddField(
            model_name='userfavoriteslist',
            name='favorited_products',
            field=models.ManyToManyField(related_name='userfavoriteslists', to='products.Product'),
        ),
    ]
