# Generated by Django 3.2.4 on 2021-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=False, max_length=254)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
